### ISSUE TITLE
Conda env installs correctly but fails on poetry build step

### ISSUE THREAD

**Issue by MTDouglas** [ncsa/NEAT#105]
**Describe the bug**
After activating the conda environment with neat in it and using `poetry build` it is unable to find the neat package

**To Reproduce**
1.`conda env create -f neat_environment.yml -n neat_v4`
2. `conda activate neat_v4` 
3. `poetry build`
Error produced: 
`Building neat (4.0)
  - Building sdist

No file/folder found for package neat`

**Expected behavior**
Poetry build step should run without errors.

This is being done in a linux/HPC enviroment. Thanks

**Comment by joshfactorial** [comment]
Working on building a fresh environment to test this on an HPC.

**Comment by joshfactorial** [comment]
Okay, I was able to get it to run the install command, but I'll keep looking to make sure I don't have a hidden dependency. things to check:

- pull the latest from main. We have had some bug fixes that are not yet in a release (pending)
- Run the poetry command from the repository home (e.g., cd /my/repo/path/NEAT; poetry install since it will rely on the lock files in the repo. There may be a way to specify this with the poetry build command (check poetry docs)
- let's try posting the conda env list of packages and I can check against what I have.

**Comment by joshfactorial** [comment]
I pushed an update to main to clean up the enivronment a little. That may help.

**Comment by MTDouglas** [comment]
Our solutions architect discovered the following (in reference to my own base):

_There is a python issue in the base with NEAT :_
`ERROR: Package 'neat' requires a different Python: 3.8.12 not in '<4.0,>=3.10'  `

He was then able to fix the issue from there and install it properly for me.
