### ISSUE TITLE
Provide the algorithm used to create BAM files

### ISSUE THREAD

**Issue by joys8998** [ncsa/NEAT#16]
**Hi there, first of all thank you for this repo is amazing and saves me a lot of time for benchmarking!**
My problem is related to the algorithm used to create the gold bam file. Indeed I used `Picard CompareSAMs` to check the gold standard bam and the bam created manually from the fastqs and I see a lot of difference.

Steps:
A) I created simulated data (the bed file is a single row bed file `chr21\t0\t46709983`)
`python gen_reads.py  -r hg38.analysisSet.fa  -R 150 -o ../NEAT --bam --vcf  --pe 300 30   -tr chr21.hg38.bed`
B) I trimmed the fastqs
`fastp --thread 16 --detect_adapter_for_pe -i read1.fastq.gz -I read2.fastq.gz -o trimmed_read1.fastq.gz -O trimmed_read2.fastq.gz -h trimmed.rep_html -j trimmed..rep_json`
C) Aligned with bwa-mem2
 `bwa-mem2 mem -R '@RG\\tID:A1\\tSM:NEAT\\tLB:lib1\\tPU:run1\\tPL:ILLUMINA' -Y -K 100000000 -M -t 32 hg38.analysisSet.fa read1.fastq.gz read2.fastq.gz -o aligned.sam`
D) sort 
`samtools view -Shb -@ 5 aligned.sam  | samtools sort -@ 5 -m 5G - > aligned.bam     samtools index aligned.bam`

E) Compare results 
`gatk CompareSAMs aligned.bam gold.bam --LENIENT_HEADER true -O compare.tsv`

The output I get is 
MAPPING_MATCH: 1800623
MAPPINGS_DIFFER: 749533
ARE_EQUAL: NO

Thus I was wondering which is the algorithms used to create bam files and how to reproduce it.

Thank you very much

**Comment by joshfactorial** [comment]
The algorithm is to replace random bases with new values, either as a sequencing error or as a true variant. Both are tracked. But, this means that variants can get inserted in areas of the genome that don't have any actual biological significance, or in regions that are very difficult for bwa to align (usually due to repetitive areas). We recommend using available mappability track beds to narrow down the comparisons. The golden BAM is the exact alignment based on the region of the reference where the mutation was inserted.

**Comment by joshfactorial** [comment]
I have noticed in my own runs that bwa alignment can be very far off what NEAT says. Part of this is because NEAT ignores scaffolds in HG38 and basically ignores hard-masked regions ("NNNNN'"). I am working on updates to address these issues.
