### ISSUE TITLE
Number of variants generated from mutational model lower than expected

### ISSUE THREAD

**Issue by aldosr** [ncsa/NEAT#51]
Hi,
I'm generating tumor reads using the same code described in #49 and bypassing the error using a simple try-except.
Anyway, the number of mutations inserted (153) are considerably lower than the original input tumor dataset (~56.000), from which the mutational model is generated.
Looking into the [code](https://github.com/ncsa/NEAT/blob/c7751fcd73023b2a19f213e411be1644bbc184ca/source/SequenceContainer.py#L404), if I'm not wrong, the number of variants, generated with the poisson distribution, are lowered. 

Do you think the number of mutations generated is correct or there is a bug in the mutational model / artificial reads generation?
Thanks a lot.

**Comment by joshfactorial** [comment]
We had an issue with the poisson list previously, where it skewed the number of variants too low, but I pushed a fix a week or two ago. Which version of the code are you using?

**Comment by joshfactorial** [comment]
It turns out that the poisson list function was working as expected. What you're seeing in init_poisson is the calculation of the subset of mutations in the current window, not the calculation for the entire chromosome. When you ran gen_mut_model on your samples, it should have given an output such as:

```
p(snp)   = 0.3
p(indel) = 0.1
overall average mut rate: 0.00623
total variants processed: 23984
```

If you can find that, please post your numbers. It would be helpful to compare to the number of records in the input vcf, so please supply that. If you do not have the above output, try running:

```
pickle.load(gzip.open('models/errorModel.pickle.gz', 'r'))[4]
```
using your generated error model as input, and that should give the average mutation rate calculated by the function. Seeing the calculated rate and the # processed v # supplied may help us identify any errors in that script.

Finally, is the mutation count you gave based on the count in the golden vcf output? Or calculated by some other means?
