### ISSUE TITLE
Easy way to specify not to simulate indels in the mutation model?

### ISSUE THREAD

**Issue by gwct** [ncsa/NEAT#85]
Hello,
I'm wondering if there is some way that I'm not seeing to tell NEAT to only insert SNPs and not indels while it is simulating reads? I'm using v3.2.

Thanks!

**Comment by joshfactorial** [comment]
Neat doesn't have a flag for this (though potentially this is a feature we could add), but you can do it one of two ways. the First would be to generate a custom mutation model with an existing vcf (just filter out the indels first, so it only sees snps). This will result in NEAT setting indel percentage to 0. There is also a pre-built model "models/MutModel_NA12878_noIndel.pickle.gz" which should produce a no-indel result, but it is geared towards human data, so that may not fit your use case.

-Josh

________________________________
From: Gregg Thomas ***@***.***>
Sent: Monday, October 2, 2023 3:00 PM
To: ncsa/NEAT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ncsa/NEAT] Easy way to specify not to simulate indels in the mutation model? (Issue #85)


Hello,
I'm wondering if there is some way that I'm not seeing to tell NEAT to only insert SNPs and not indels while it is simulating reads? I'm using v3.2.

Thanks!

**Comment by gwct** [comment]
Ok, thanks. I think the human-based model should be fine -- I just need something without indels. I do agree that a `--noindel` flag would be really convenient.

Otherwise, are there examples of model files somewhere such that I could create my own if I wanted? I see the pickled ones, but I don't know of an easy way to view those. 

Thanks again!

**Comment by joshfactorial** [comment]
in the Utilities folder, there is a utility called gen_mut_model.py. The idea is that it will read in your real vcf data (you'll need the reference as well) and then generate a mutation model pickle file that can be used as input to NEAT using the -m flag (lower case). You can use the no-indel model in that way.

example:

python gen_mut_model.py -m my_variants.vcf -r my_ref.fa -o models/no-indel

python gen_reads.py -m models/no-indel.pickle -r my_ref.fa -c 10

Pickle is just a way to store a python object in a file, so the files themselves are either just lists of numbers or a class instance, but basically indecipherable without knowing the details of the code.


________________________________

**Comment by gwct** [comment]
Got it, thanks. I was hoping there'd be some plain text files with the mutation distributions that I could look at, but if the data structures are more complex that's understandable.

Thanks!

**Comment by joshfactorial** [comment]
There is a plot mut model function that can do some visualizations, but it's untested and I can't even say for sure if it works. That's a point of development at the moment.

-Josh
________________________________
