### ISSUE TITLE
Re evaluation of alignment bam files failed when calling with variant calling

### ISSUE THREAD

**Issue by shafayetrahat** [ncsa/NEAT#88]
**Describe the bug**
I was going to re-evaluate the gold standard .sam file and try to generate a "variant calling" to check if it agrees with the variant calling. The variant calling is running with no error. 
![image](https://github.com/ncsa/NEAT/assets/12217769/e418a246-c3a8-4586-b191-b1370e0c4fb4)
However, the vcf file is empty. So, I am wondering if the reads file contains any variants. 
![image](https://github.com/ncsa/NEAT/assets/12217769/8a3a51a7-1417-4b76-979f-136bfc8afa80)
**To Reproduce**
1. Command to get gold-standard files 
![image](https://github.com/ncsa/NEAT/assets/12217769/4e5ac7f8-37b9-4a14-a25e-ab2b9803251e)

3. gatk HaplotypeCaller command
![image](https://github.com/ncsa/NEAT/assets/12217769/6fe96445-ecf0-4583-9108-381af2978d1d)

**Expected behavior**
A vcf file with variants from alignment .bam file

**Additional context**
**Does the alignment .bam file needs any kind of preprocessing before variant calling?**

**Comment by joshfactorial** [comment]
Okay, I see in the NEAT call you set random mutation to 0, so it will only insert mutations from the input vcf file. First, I would check that the names in the bam file match the names in the VCF. NEAT sometimes has trouble with chromosome names. If it doesn't detect a name match or if the VCF has a ref that doesn't match the reference allele, it will not add them. You should see some indication of that in the output from running NEAT. If NEAT filtered out all the VCF variants, or gave them low-quality scores, and also didn't add mutations, then HaplotypeCaller is correct (all other variants NEAT adds should show up as errors/low-quality reads/noise and get filtered out). So, first thing is to make sure NEAT is even adding anything.

Next, you might try changing the minimum quality score, to see if the variants are present at all or if they are getting filtered out by HaplotypeCaller. It might be worth looking at the BAM files in a genome browser, too, to see if the intended variants are present.

-Josh

________________________________
From: Shafayet Islam ***@***.***>
Sent: Wednesday, October 25, 2023 10:51 AM
To: ncsa/NEAT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ncsa/NEAT] Re evaluation of alignment bam files failed when calling with variant calling (Issue #88)


Describe the bug
I was going to re-evaluate the gold standard .sam file and try to generate a "variant calling" to check if it agrees with the variant calling. The variant calling is running with no error.
[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/12217769/278069447-e418a246-c3a8-4586-b191-b1370e0c4fb4.png__;!!DZ3fjg!5DfRqRzkNx5fLHoarWVyYo6Nxj4xLFvsqF4q6ApwvhyXvIBlCJ9yGJq2hQY0sbJcadAbC6mZrZXSVJkxkWKTVrwpfwwsyQ$>
However, the vcf file is empty. So, I am wondering if the reads file contains any variants.
[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/12217769/278069961-8a3a51a7-1417-4b76-979f-136bfc8afa80.png__;!!DZ3fjg!5DfRqRzkNx5fLHoarWVyYo6Nxj4xLFvsqF4q6ApwvhyXvIBlCJ9yGJq2hQY0sbJcadAbC6mZrZXSVJkxkWKTVrxvNs6k5g$>
To Reproduce

  1.  Command to get gold-standard files
[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/12217769/278071236-4e5ac7f8-37b9-4a14-a25e-ab2b9803251e.png__;!!DZ3fjg!5DfRqRzkNx5fLHoarWVyYo6Nxj4xLFvsqF4q6ApwvhyXvIBlCJ9yGJq2hQY0sbJcadAbC6mZrZXSVJkxkWKTVrzRqkfo_w$>

  2.  gatk HaplotypeCaller command
[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/12217769/278070435-6fe96445-ecf0-4583-9108-381af2978d1d.png__;!!DZ3fjg!5DfRqRzkNx5fLHoarWVyYo6Nxj4xLFvsqF4q6ApwvhyXvIBlCJ9yGJq2hQY0sbJcadAbC6mZrZXSVJkxkWKTVrzKz4jTcw$>

Expected behavior
A vcf file with variants from alignment .bam file

Additional context
Does the alignment .bam file needs any kind of preprocessing before variant calling?

**Comment by shafayetrahat** [comment]
Is there any to control the quality of the reads?

**Comment by shafayetrahat** [comment]
I checked the bam file using IGV. Variant are present in the bam file. However, their quality read seem to be poor. Is there any way to control the quality of the reads?
![image](https://github.com/ncsa/NEAT/assets/12217769/3f9818f8-f172-402c-b50d-c1b780c18b26)

**Comment by shafayetrahat** [comment]
Sorry, I am correcting myself. bcftools can generate variants. However, GATK4 can't. That's a really interesting problem.

**Comment by joshfactorial** [comment]
No, not really. In the new version of NEAT, I've been trying copying the quality from input vcfs and making sure added variants have high quality, so they are more clear. It was all just randomly generated in this version, but the new version isn't fully working yet.

**Comment by shafayetrahat** [comment]
Ok, but why gatk4 isn't generating any single variant? I am still trying to understand why it is happening. I am attaching the NEAT generated .bam file for reference 
https://www.dropbox.com/scl/fi/3v36cp6uu15gqvyo4xdyt/sim_reads_golden.bam?rlkey=fixm8z08trr8a8jaqui9epoin&dl=0

**Comment by joshfactorial** [comment]
Probably because they are low-quality. I'll try to replicate with your bam and see what I can figure out.

**Comment by joshfactorial** [comment]
Okay, I have worked this together with some other fixes as part of Neat 4.2. I think we were mistranslating the quality scores. The new version will hopefully work better.

**Comment by shafayetrahat** [comment]
4.2 is not found in the repo. Do you mean 4.1.2?

**Comment by joshfactorial** [comment]
4.2 wil be ready soon!
________________________________
